### ISSUE TITLE
Share test data file in the tutorial

### ISSUE THREAD

**Issue by subercui** [JackieHanLab/TOSICA#1]
Hi, can you share the `demo_train.h5ad` data used in the [test.ipynb](https://github.com/JackieHanLab/TOSICA/blob/main/test/tutorial.ipynb)?

**Comment by JackieHanLab** [comment]
We have updated our tutorial on Github and researchers can now download demo data at the website indicated (https://figshare.com/articles/dataset/demo_data/21981011) and try TOSICA
