### ISSUE TITLE
Problem with TOSICA metrics comparing

### ISSUE THREAD

**Issue by WhatMelonGua** [JackieHanLab/TOSICA#14]
Hello! TOSICA is an interesting and great tools when annotation and integration.

here I have some problems comparing TOSICA result.
I want to compare TOSICA result with other methods (in scIB)
but when I try to use sciB:
1. I can't completely bulid the environment of scIB, 2. the scIB pipeline code doesn't clearly.
I noticed you plot a nice fig in TOSICA fig5.
so if you like share your scIB's requirement.ymal or requirement.txt file, and your run successful code, I would greatly appreciate it!

**Comment by JiaweiChenGo** [comment]
Thanks for you interest! 
If you have problems applying scIB, you can ask them for help. https://github.com/theislab/scib.
