### ISSUE TITLE
Sharing code to reproduce manuscript figures

### ISSUE THREAD

**Issue by mariemoullet** [JackieHanLab/TOSICA#2]
Hello! This is a super interesting method, I was wondering if you were planning on releasing the code used to generate the figures in the manuscript, or update the tutorial to show how to pull out population-specific pathways (eg Fig4)? Thank you so much for your help!

**Comment by JackieHanLab** [comment]
Thanks for your appreciation, we may release supplementary code to reproduce all the analyses presented in the TOSICA paper in the future. For now, we have summarized the codes for fig4 in [reproducibility](https://github.com/JackieHanLab/TOSICA/tree/main/reproducibility), which include how we choose those pathways. Actually, we just used `scanpy.tl.rank_genes_groups(method='wilcoxon')` to find population-specific pathways and Spearman/Pearson correlation coefficient to find pathways associated with continuous variables. 
Hope the answer can help you!
