### ISSUE TITLE
[bug] There is a bug when I install the software

### ISSUE THREAD

**Issue by yang050036** [JackieHanLab/TOSICA#6]
I installed python 3.8, but I get an error running `pip install .`:
`ERROR: Package 'TOSICA' requires a different Python: 3.6.15 not in '>=3.8'`
Are there any bugs here？

**Comment by JackieHanLab** [comment]
Thank you for your interest in TOSICA. It seems that you did not successfully install python 3.8, because this error appears when the Python version in your current environment is 3.6.15 instead of 3.8. You can check the Python version in your current environment.

**Comment by yang050036** [comment]
Yes, thanks for you reply. I find the error is produced by the ~/.bashrc.  The conda's python is overwritten in ~/.bashrc,  and it work well when I revise the file.
