### ISSUE TITLE
could you share what's hardware(GPU) used to train this model?

### ISSUE THREAD

**Issue by rushrush2022** [JackieHanLab/TOSICA#7]
@JackieHanLab 

thanks very much for you to share the codes, could you share what's hardware(mostly GPU) configuration used to train these models mentioned in paper?
what's the time used ?

thanks again!!

**Comment by rushrush2022** [comment]
From tutorial.ipynb, I see "NVIDIA GeForce RTX 3080 Ti Laptop GPU"

**Comment by JiaweiChenGo** [comment]
In single `Tesla V100-SXM2-32GB`: train 85~90 cells/s and predict ~2500 cells/s;
In single `RTX 3080 Ti Laptop GPU 16G`: train ~70 cells/s and predict ~2000 cells/s
