### ISSUE TITLE
Questions about reading certain datasets

### ISSUE THREAD

**Issue by HelloWorldLTY** [JackieHanLab/TOSICA#8]
Hi, I look for some datasets you used in this paper and for one particular datasets,GSE1159677, I find some errors when I intend to use read_h5f based on either scanpy or pandas.
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/43333475/232534259-c25a0d7a-6f10-47aa-b07e-a82f7f56de63.png">

By using sc.read_10x_h5

Did you use seurat to read this file? I think the problem is caused by the sparse or storage. The count information here is a one d vector. Thanks a lot.

**Comment by JackieHanLab** [comment]
For data GSE159677, we downloaded the 10X featurebcmatrixfiltered.tar files in the GSE159677_RAW.tar, and used Seurat for their pre-processing.
